# Backend/Business_Layer/services/vendor_service.py
import datetime
import logging
from typing import List, Optional

import requests

from Backend.API_Layer.interface.vendor_interface import (
    VendorAddressCreateRequest,
    VendorAddressUpdateRequest,
    VendorBankCreateRequest,
    VendorBankUpdateRequest,
    VendorCreateRequest,
    VendorTaxCreateRequest,
    VendorTaxUpdateRequest,
    VendorUpdateRequest,
)
from Backend.Business_Layer.utils.gst_service import search_gstin
from Backend.Business_Layer.utils.vendor_validator import (
    validate_bank_account_holder_name,
    validate_bank_account_number,
    validate_email,
    validate_ifsc,
    validate_pan,
    validate_phone_number,
    validate_vendor_name,
)
from Backend.Data_Access_Layer.dao.vendor_dao import VendorDAO
from Backend.Data_Access_Layer.models.audit import AuditLog
from Backend.Data_Access_Layer.models.vendor import Vendor, VendorAddress, VendorBank, VendorTax

VENDOR_STATUS_MODULE = "VENDOR"
DEFAULT_VENDOR_STATUS_CODE = "PENDING"
VENDOR_CODE_GENERATION_ATTEMPTS = 5
BANK_DUPLICATE_ACROSS_VENDORS_CONFIG_KEY = "VENDOR_BANK_DUPLICATE_ACROSS_VENDORS"

logger = logging.getLogger(__name__)


class VendorService:
    def __init__(self, db):
        self.db = db
        self.vendor_dao = VendorDAO(db)

    # =========================================================
    # Vendor
    # =========================================================
    # vendor is generated by vendor name one letter of each word in vendor name and a random 4 digit number. If the generated vendor code already exists, it will generate a new one until it finds a unique code.
    def generate_vendor_code(self, vendor_name: str) -> str:
        vendor_code = "".join(
            [word[0] for word in vendor_name.split(" ")]
        ) + str(datetime.datetime.now().strftime("%Y%m%d%H%M%S"))[-4:]
        return vendor_code

    def _generate_unique_vendor_code(self, vendor_name: str) -> str:
        for attempt in range(VENDOR_CODE_GENERATION_ATTEMPTS):
            candidate = self.generate_vendor_code(vendor_name)
            if attempt > 0:
                candidate = f"{candidate}{attempt}"
            if not self.vendor_dao.vendor_code_exists(candidate):
                return candidate

        raise ValueError("Unable to generate a unique vendor_code, please retry")

    @staticmethod
    def _verify_gstin(gstin: str) -> None:
        try:
            search_gstin(gstin)
        except requests.exceptions.HTTPError as exc:
            raise ValueError(f"GSTIN verification failed for '{gstin}': {exc}")
        except requests.exceptions.RequestException as exc:
            raise ValueError(f"GSTIN verification unavailable: {exc}")

    def create_vendor(self, vendor_data: VendorCreateRequest, user_id: str) -> Vendor:

        is_gst_verified = bool(vendor_data.gstin)
        if is_gst_verified:
            self._verify_gstin(vendor_data.gstin)

        vendor_name = validate_vendor_name(vendor_data.vendor_name, strict=not is_gst_verified)

        if self.vendor_dao.vendor_name_exists(vendor_name):
            raise ValueError("A vendor with this name already exists")


        if not self.vendor_dao.country_exists(vendor_data.country_id):
            raise ValueError("Country not found for the given country_id")

        if (
            vendor_data.currency_id is not None
            and not self.vendor_dao.currency_exists(vendor_data.currency_id)
        ):
            raise ValueError("Currency not found for the given currency_id")

        if (
            vendor_data.payment_term_id is not None
            and not self.vendor_dao.payment_term_exists(vendor_data.payment_term_id)
        ):
            raise ValueError("Payment term not found for the given payment_term_id")

        pan_number = None
        if vendor_data.pan_number:
            pan_number = validate_pan(vendor_data.pan_number, strict=not is_gst_verified)
            if self.vendor_dao.pan_number_exists(pan_number):
                raise ValueError("A vendor with this PAN number already exists")

        phone_number = None
        if vendor_data.phone_number:
            phone_number = validate_phone_number(vendor_data.phone_number)
            if self.vendor_dao.phone_number_exists(phone_number):
                raise ValueError("A vendor with this phone number already exists")

        vendor_code = self._generate_unique_vendor_code(vendor_name)

        email = None
        if vendor_data.email:
            email = validate_email(vendor_data.email)
            if self.vendor_dao.email_exists(email):
                raise ValueError("A vendor with this email already exists")

        status_id = self._resolve_status_id(vendor_data.status_id)

        vendor = Vendor(
            vendor_name=vendor_name,
            vendor_code=vendor_code,
            country_id=vendor_data.country_id,
            payment_term_id=vendor_data.payment_term_id,
            currency_id=vendor_data.currency_id,
            pan_number=pan_number,
            phone_number=phone_number,
            email=email,
            status_id=status_id,
            created_by=user_id,
            updated_by=user_id,
        )

        self.vendor_dao.create_vendor(vendor)

        self._write_audit(
            table_name="vendor",
            record_id=vendor.vendor_id,
            action="CREATE",
            changed_by=user_id,
            new_values=self._snapshot(vendor),
        )

        self.db.commit()
        self.db.refresh(vendor)

        return vendor

    def get_vendor(self, vendor_id: int) -> Vendor:
        vendor = self.vendor_dao.get_vendor_by_id(vendor_id)

        if vendor is None:
            raise ValueError("Vendor not found")

        return vendor

    def list_vendors(
        self,
        status_id: Optional[int] = None,
        country_id: Optional[int] = None,
        search: Optional[str] = None,
        skip: int = 0,
        limit: int = 100,
    ) -> List[Vendor]:

        return self.vendor_dao.get_all_vendors(status_id, country_id, search, skip, limit)

    # =========================================================
    # Vendor-scoped collections
    #
    # These do not re-implement NDA, goods-receipt or purchase-order logic -
    # each one delegates to that module's existing service, so the items
    # returned here are the same objects (and the same eager-loading) as the
    # module's own endpoint returns. The services are imported inside the
    # methods because nda_service reaches s3_utils, which imports boto3 and
    # reads AWS_* at module scope - the same lazy-import rule nda_service
    # itself follows.
    # =========================================================

    def list_ndas(self, vendor_id: int) -> List[object]:
        """Every NDA on file for this vendor, newest first. Empty list when
        the vendor has none."""

        self._require_vendor(vendor_id)

        from Backend.Business_Layer.services.nda_service import NdaService

        return NdaService(self.db).list_for_vendor(vendor_id)

    def list_goods_receipts(
        self,
        vendor_id: int,
        skip: int = 0,
        limit: int = 100,
    ) -> List[object]:
        """Goods receipts recorded against this vendor. Empty list when the
        vendor has none."""

        self._require_vendor(vendor_id)

        from Backend.Business_Layer.services.goods_receipt_service import GoodsReceiptService

        return GoodsReceiptService(self.db).list_goods_receipts(
            vendor_id=vendor_id, po_id=None, skip=skip, limit=limit
        )

    def list_purchase_orders_for_vendor(
        self,
        vendor_id: int,
        skip: int = 0,
        limit: int = 100,
    ) -> List[object]:
        """Purchase orders raised on this vendor, via the existing
        PurchaseOrderService filter that GET /apm/purchase-order?vendor_id=
        also uses."""

        self._require_vendor(vendor_id)

        from Backend.Business_Layer.services.purchase_order_service import PurchaseOrderService

        return PurchaseOrderService(self.db).list_purchase_orders(
            vendor_id=vendor_id, skip=skip, limit=limit
        )

    def list_documents(self, vendor_id: int, expires_in: Optional[int] = None) -> List[dict]:
        """This vendor's general (non-NDA) documents.

        No vendor_document table is involved: this reads the file references
        that quotations/POs, goods receipts and invoice attachments already
        carry. Four flat queries total, whatever the row count.

        NDA DOCUMENTS ARE DELIBERATELY EXCLUDED. The NDA workflow owns its own
        files and exposes them through GET /apm/vendor/{vendor_id}/ndas and
        GET /apm/nda/{nda_id}/document, which carry the NDA's status, scope,
        validity and sent/signed dates alongside the file. Listing the same
        PDFs here as well only duplicated that tab with none of its context.
        Nothing is deleted or altered - ap.vendor_nda and its objects are read
        here purely to know which keys to leave out.

        The exclusion is driven by the NDA records themselves
        (``vendor_nda.document_key`` / ``signed_document_key``), never by
        guessing at a filename or a path prefix. That also means an NDA object
        referenced from some OTHER file-bearing row - a generic document or
        file-reference table now or later - is still recognised as an NDA file
        and dropped, because every candidate is matched against the vendor's
        own NDA keys before it is added.

        Each entry carries a short-lived presigned GET URL rather than the S3
        object key, so the bucket stays private and no key is handed to the
        client. Minting a URL is a local signing operation, not a network
        call, so doing it per row costs nothing. If S3 is not configured the
        documents are still listed, with ``url`` left None, because the
        inventory is useful even when a link cannot be handed out.
        """

        self._require_vendor(vendor_id)

        sign, ttl = self._presigner(expires_in)

        documents: List[dict] = []

        # Every object key the NDA workflow owns for this vendor, taken from
        # the NDA records themselves. Built once, then consulted for every
        # candidate below - so an NDA file is excluded no matter which table
        # happens to reference it.
        nda_keys = self._nda_document_keys(vendor_id)

        def add(document_type, source_id, reference, file_reference, document_date, file_name=None):
            """Append one entry, skipping anything that has no usable file
            reference, anything owned by the NDA workflow, and swallowing a
            single malformed row.

            One bad record must never turn the whole inventory into a 500 -
            the other documents are still worth returning.
            """

            if not file_reference:
                return
            if self._is_nda_document(file_reference, nda_keys):
                return
            try:
                entry = self._document_entry(
                    document_type, source_id, reference, file_reference, document_date, sign, ttl
                )
            except Exception:
                logger.warning(
                    "Skipping unreadable %s document for vendor %s", document_type, vendor_id,
                    exc_info=True,
                )
                return
            if file_name:
                entry["file_name"] = file_name
            documents.append(entry)

        # Procurement-side document. ap.purchase_order carries no file column
        # and there is no purchase_order_attachment table, so the document a
        # PO can actually reach is the quotation it was raised from; the PO
        # number rides along as the reference when one exists.
        for quotation_id, quotation_number, po_number, file_url, quotation_date in self.vendor_dao.get_quotation_documents(vendor_id):
            add("QUOTATION", quotation_id, po_number or quotation_number, file_url, quotation_date)

        for grn_id, grn_number, file_path, receipt_date in self.vendor_dao.get_goods_receipt_documents(vendor_id):
            add("GOODS_RECEIPT", grn_id, grn_number, file_path, receipt_date)

        # No NDA loop here on purpose: the NDA tab (list_ndas) is the single
        # source for NDA records and their generated/signed documents.

        for invoice_id, invoice_number, file_name, file_path, uploaded_at in self.vendor_dao.get_invoice_attachment_documents(vendor_id):
            # The attachment record stores its own original filename; prefer
            # it over the one derived from the object key.
            add(
                "INVOICE_ATTACHMENT", invoice_id, invoice_number, file_path, uploaded_at,
                file_name=file_name,
            )

        return documents

    def _nda_document_keys(self, vendor_id: int) -> set:
        """The S3 object keys of every generated and signed NDA this vendor
        has, from ap.vendor_nda - the NDA module's own record of what it owns.

        Keys are normalised (stripped, leading "/" removed) so a reference
        stored with different surrounding whitespace or a leading slash still
        matches. Comparison stays exact-key based: no filename or path-prefix
        heuristic decides whether a document belongs to the NDA workflow.
        """

        keys = set()

        for _nda_id, document_key, signed_key, _created_at in self.vendor_dao.get_nda_documents(vendor_id):
            for key in (document_key, signed_key):
                normalised = self._normalise_key(key)
                if normalised:
                    keys.add(normalised)

        return keys

    @staticmethod
    def _normalise_key(file_reference) -> Optional[str]:
        if not file_reference or not isinstance(file_reference, str):
            return None
        return file_reference.strip().lstrip("/") or None

    @classmethod
    def _is_nda_document(cls, file_reference, nda_keys: set) -> bool:
        """True when this file reference is one the NDA workflow owns."""

        if not nda_keys:
            return False
        return cls._normalise_key(file_reference) in nda_keys

    @staticmethod
    def _document_entry(document_type, source_id, reference, file_path, document_date, sign, ttl) -> dict:
        url = sign(file_path)
        return {
            "document_type": document_type,
            "source_id": source_id,
            "reference": reference,
            # Derived from the key's last segment - the key itself is never
            # returned to the client.
            "file_name": file_path.split("/")[-1] if file_path else None,
            "url": url,
            "url_expires_in_seconds": ttl if url else None,
            "document_date": document_date,
        }

    @staticmethod
    def _presigner(expires_in: Optional[int]):
        """Returns (sign, ttl). ``sign`` maps an object key to a short-lived
        URL, or to None when S3 is unavailable or the key is unusable."""

        try:
            from Backend.API_Layer.utils.s3_utils import (
                DEFAULT_PRESIGNED_URL_TTL_SECONDS,
                generate_presigned_url,
            )
        except Exception:
            # No boto3 / no AWS configuration: list the documents without URLs
            # rather than failing the whole request.
            return (lambda key: None), None

        ttl = int(expires_in or DEFAULT_PRESIGNED_URL_TTL_SECONDS)

        def sign(key: Optional[str]) -> Optional[str]:
            if not key:
                return None
            try:
                return generate_presigned_url(key, expires_in=ttl)
            except Exception:
                return None

        return sign, ttl

    def update_vendor(
        self,
        vendor_id: int,
        update_data: VendorUpdateRequest,
        user_id: str,
    ) -> Vendor:

        vendor = self.vendor_dao.get_vendor_by_id(vendor_id)

        if vendor is None:
            raise ValueError("Vendor not found")

        before = self._snapshot(vendor)

        if update_data.vendor_name is not None:
            vendor_name = validate_vendor_name(update_data.vendor_name)
            if self.vendor_dao.vendor_name_exists(vendor_name, exclude_vendor_id=vendor_id):
                raise ValueError("A vendor with this name already exists")
            vendor.vendor_name = vendor_name

        # vendor_code is backend-generated only and is not editable via this
        # endpoint; update_data.vendor_code (if sent) is intentionally ignored.

        if update_data.country_id is not None:
            if not self.vendor_dao.country_exists(update_data.country_id):
                raise ValueError("Country not found for the given country_id")
            vendor.country_id = update_data.country_id

        if update_data.payment_term_id is not None:
            if not self.vendor_dao.payment_term_exists(update_data.payment_term_id):
                raise ValueError("Payment term not found for the given payment_term_id")
            vendor.payment_term_id = update_data.payment_term_id

        if update_data.currency_id is not None:
            if not self.vendor_dao.currency_exists(update_data.currency_id):
                raise ValueError("Currency not found for the given currency_id")
            vendor.currency_id = update_data.currency_id

        if update_data.pan_number is not None:
            pan_number = validate_pan(update_data.pan_number)
            if self.vendor_dao.pan_number_exists(pan_number, exclude_vendor_id=vendor_id):
                raise ValueError("A vendor with this PAN number already exists")
            vendor.pan_number = pan_number

        if update_data.phone_number is not None:
            phone_number = validate_phone_number(update_data.phone_number)
            if self.vendor_dao.phone_number_exists(phone_number, exclude_vendor_id=vendor_id):
                raise ValueError("A vendor with this phone number already exists")
            vendor.phone_number = phone_number

        if update_data.email is not None:
            email = validate_email(update_data.email)
            if self.vendor_dao.email_exists(email, exclude_vendor_id=vendor_id):
                raise ValueError("A vendor with this email already exists")
            vendor.email = email

        if update_data.status_id is not None:
            vendor.status_id = self._resolve_status_id(update_data.status_id)

        vendor.updated_by = user_id

        after = self._snapshot(vendor)
        changed = {key: value for key, value in after.items() if before.get(key) != value}

        if changed:
            self._write_audit(
                table_name="vendor",
                record_id=vendor.vendor_id,
                action="UPDATE",
                changed_by=user_id,
                old_values={key: before.get(key) for key in changed},
                new_values=changed,
            )

        self.db.commit()
        self.db.refresh(vendor)

        return vendor

    def change_status(self, vendor_id: int, is_active: bool, user_id: str) -> Vendor:

        vendor = self.vendor_dao.get_vendor_by_id(vendor_id)

        if vendor is None:
            raise ValueError("Vendor not found")

        target_code = "ACTIVE" if is_active else "INACTIVE"
        target_status = self.vendor_dao.get_status_by_module_code(
            VENDOR_STATUS_MODULE, target_code
        )

        if target_status is None:
            raise ValueError(
                f"'{target_code}' status is not configured for the {VENDOR_STATUS_MODULE} module"
            )

        old_status_id = vendor.status_id
        vendor.status_id = target_status.status_id
        vendor.updated_by = user_id

        self._write_audit(
            table_name="vendor",
            record_id=vendor.vendor_id,
            action="STATUS_CHANGE",
            changed_by=user_id,
            old_values={"status_id": old_status_id},
            new_values={
                "status_id": target_status.status_id,
                "status_code": target_status.status_code,
            },
        )

        self.db.commit()
        self.db.refresh(vendor)

        return vendor

    # =========================================================
    # Vendor Address
    # =========================================================

    def create_address(
        self,
        vendor_id: int,
        data: VendorAddressCreateRequest,
        user_id: str,
    ) -> VendorAddress:

        self._require_vendor(vendor_id)
        self._validate_address_fields(data.address_line1, data.city)
        self._require_address_country(data.country_id)

        is_primary = data.is_primary
        if not is_primary:
            existing = self.vendor_dao.get_addresses_by_vendor(vendor_id)
            if not any(address.is_primary for address in existing):
                is_primary = True

        if is_primary:
            self.vendor_dao.unset_primary_addresses(vendor_id)

        address = VendorAddress(
            vendor_id=vendor_id,
            address_type=data.address_type,
            address_line1=data.address_line1,
            address_line2=data.address_line2,
            city=data.city,
            state=data.state,
            postal_code=data.postal_code,
            country_id=data.country_id,
            is_primary=is_primary,
        )
        self.vendor_dao.create_vendor_address(address)

        self._write_audit(
            table_name="vendor_address",
            record_id=address.vendor_address_id,
            action="CREATE",
            changed_by=user_id,
            new_values=self._address_snapshot(address),
        )

        self.db.commit()
        self.db.refresh(address)

        return address

    def list_addresses(self, vendor_id: int) -> List[VendorAddress]:
        self._require_vendor(vendor_id)
        return self.vendor_dao.get_addresses_by_vendor(vendor_id)

    def get_address(self, vendor_id: int, vendor_address_id: int) -> VendorAddress:
        self._require_vendor(vendor_id)
        address = self.vendor_dao.get_vendor_address_by_id(vendor_id, vendor_address_id)
        if address is None:
            raise ValueError("Address not found")
        return address

    def update_address(
        self,
        vendor_id: int,
        vendor_address_id: int,
        data: VendorAddressUpdateRequest,
        user_id: str,
    ) -> VendorAddress:

        self._require_vendor(vendor_id)
        address = self.vendor_dao.get_vendor_address_by_id(vendor_id, vendor_address_id)
        if address is None:
            raise ValueError("Address not found")

        before = self._address_snapshot(address)

        if data.address_type is not None:
            address.address_type = data.address_type
        if data.address_line1 is not None:
            if not data.address_line1.strip():
                raise ValueError("address_line1 is required for a vendor address")
            address.address_line1 = data.address_line1
        if data.address_line2 is not None:
            address.address_line2 = data.address_line2
        if data.city is not None:
            if not data.city.strip():
                raise ValueError("city is required for a vendor address")
            address.city = data.city
        if data.state is not None:
            address.state = data.state
        if data.postal_code is not None:
            address.postal_code = data.postal_code
        if data.country_id is not None:
            self._require_address_country(data.country_id)
            address.country_id = data.country_id

        if data.is_primary is True and not address.is_primary:
            self.vendor_dao.unset_primary_addresses(vendor_id)
            address.is_primary = True
        elif data.is_primary is False:
            address.is_primary = False

        after = self._address_snapshot(address)
        changed = {key: value for key, value in after.items() if before.get(key) != value}

        if changed:
            self._write_audit(
                table_name="vendor_address",
                record_id=address.vendor_address_id,
                action="UPDATE",
                changed_by=user_id,
                old_values={key: before.get(key) for key in changed},
                new_values=changed,
            )

        self.db.commit()
        self.db.refresh(address)

        return address

    def delete_address(self, vendor_id: int, vendor_address_id: int, user_id: str) -> None:
        self._require_vendor(vendor_id)
        address = self.vendor_dao.get_vendor_address_by_id(vendor_id, vendor_address_id)
        if address is None:
            raise ValueError("Address not found")

        self._write_audit(
            table_name="vendor_address",
            record_id=address.vendor_address_id,
            action="DELETE",
            changed_by=user_id,
            old_values=self._address_snapshot(address),
        )

        self.vendor_dao.delete_vendor_address(address)
        self.db.commit()

    @staticmethod
    def _validate_address_fields(address_line1: str, city: str) -> None:
        if not address_line1.strip():
            raise ValueError("address_line1 is required for a vendor address")
        if not city.strip():
            raise ValueError("city is required for a vendor address")

    def _require_address_country(self, country_id: int) -> None:
        if not self.vendor_dao.country_exists(country_id):
            raise ValueError(f"Country not found for address country_id={country_id}")

    @staticmethod
    def _address_snapshot(address: VendorAddress) -> dict:
        return {
            "address_type": address.address_type,
            "address_line1": address.address_line1,
            "address_line2": address.address_line2,
            "city": address.city,
            "state": address.state,
            "postal_code": address.postal_code,
            "country_id": address.country_id,
            "is_primary": address.is_primary,
        }

    # =========================================================
    # Vendor Bank
    # =========================================================

    def create_bank(
        self,
        vendor_id: int,
        data: VendorBankCreateRequest,
        user_id: str,
    ) -> VendorBank:

        self._require_vendor(vendor_id)
        self._validate_bank_fields(data.bank_name, data.account_holder_name)
        account_holder_name = validate_bank_account_holder_name(data.account_holder_name)

        account_number, ifsc_code = self._validate_bank_identifiers(
            data.account_number, data.iban, data.ifsc_code
        )
        self._check_bank_duplicates(vendor_id, account_number, data.iban)

        is_primary = data.is_primary
        if not is_primary:
            if self.vendor_dao.get_active_primary_bank(vendor_id) is None:
                is_primary = True

        if is_primary:
            # Bank accounts are versioned: close out the currently active
            # primary row instead of overwriting it, preserving history.
            existing_primary = self.vendor_dao.get_active_primary_bank(vendor_id)
            if existing_primary is not None:
                existing_primary.effective_to = datetime.date.today()
                existing_primary.is_primary = False

        bank = VendorBank(
            vendor_id=vendor_id,
            bank_name=data.bank_name,
            account_holder_name=account_holder_name,
            account_number=account_number,
            iban=data.iban,
            swift_code=data.swift_code,
            routing_number=data.routing_number,
            ifsc_code=ifsc_code,
            is_primary=is_primary,
        )
        self.vendor_dao.create_vendor_bank(bank)

        self._write_audit(
            table_name="vendor_bank",
            record_id=bank.vendor_bank_id,
            action="CREATE",
            changed_by=user_id,
            new_values=self._bank_snapshot(bank),
        )

        self.db.commit()
        self.db.refresh(bank)

        return bank

    def list_banks(self, vendor_id: int) -> List[VendorBank]:
        self._require_vendor(vendor_id)
        return self.vendor_dao.get_banks_by_vendor(vendor_id)

    def get_bank(self, vendor_id: int, vendor_bank_id: int) -> VendorBank:
        self._require_vendor(vendor_id)
        bank = self.vendor_dao.get_vendor_bank_by_id(vendor_id, vendor_bank_id)
        if bank is None:
            raise ValueError("Bank not found")
        return bank

    def update_bank(
        self,
        vendor_id: int,
        vendor_bank_id: int,
        data: VendorBankUpdateRequest,
        user_id: str,
    ) -> VendorBank:

        self._require_vendor(vendor_id)
        bank = self.vendor_dao.get_vendor_bank_by_id(vendor_id, vendor_bank_id)
        if bank is None:
            raise ValueError("Bank not found")

        before = self._bank_snapshot(bank)

        if data.bank_name is not None:
            if not data.bank_name.strip():
                raise ValueError("bank_name is required for a vendor bank account")
            bank.bank_name = data.bank_name
        if data.account_holder_name is not None:
            bank.account_holder_name = validate_bank_account_holder_name(
                data.account_holder_name
            )
        if data.account_number is not None:
            bank.account_number = validate_bank_account_number(data.account_number)
        if data.iban is not None:
            bank.iban = data.iban
        if data.swift_code is not None:
            bank.swift_code = data.swift_code
        if data.routing_number is not None:
            bank.routing_number = data.routing_number
        if data.ifsc_code is not None:
            bank.ifsc_code = validate_ifsc(data.ifsc_code)

        if data.account_number is not None or data.iban is not None:
            if not bank.account_number and not bank.iban:
                raise ValueError(
                    "At least one of account_number or iban is required for a vendor bank account"
                )
            if self.vendor_dao.account_identifier_exists_for_vendor(
                vendor_id, bank.account_number, bank.iban, exclude_bank_id=vendor_bank_id
            ):
                raise ValueError("This account_number/iban already exists for this vendor")
            if self._bank_duplicate_across_vendors_enabled() and self.vendor_dao.account_identifier_exists_across_vendors(
                bank.account_number, bank.iban, exclude_vendor_id=vendor_id
            ):
                raise ValueError("This account_number/iban already exists for another vendor")

        if data.is_primary is True and not bank.is_primary:
            existing_primary = self.vendor_dao.get_active_primary_bank(vendor_id)
            if existing_primary is not None:
                existing_primary.effective_to = datetime.date.today()
                existing_primary.is_primary = False
            bank.is_primary = True
        elif data.is_primary is False:
            bank.is_primary = False

        after = self._bank_snapshot(bank)
        changed = {key: value for key, value in after.items() if before.get(key) != value}

        if changed:
            self._write_audit(
                table_name="vendor_bank",
                record_id=bank.vendor_bank_id,
                action="UPDATE",
                changed_by=user_id,
                old_values={key: before.get(key) for key in changed},
                new_values=changed,
            )

        self.db.commit()
        self.db.refresh(bank)

        return bank

    def delete_bank(self, vendor_id: int, vendor_bank_id: int, user_id: str) -> None:
        self._require_vendor(vendor_id)
        bank = self.vendor_dao.get_vendor_bank_by_id(vendor_id, vendor_bank_id)
        if bank is None:
            raise ValueError("Bank not found")

        self._write_audit(
            table_name="vendor_bank",
            record_id=bank.vendor_bank_id,
            action="DELETE",
            changed_by=user_id,
            old_values=self._bank_snapshot(bank),
        )

        self.vendor_dao.delete_vendor_bank(bank)
        self.db.commit()

    @staticmethod
    def _validate_bank_fields(bank_name: str, account_holder_name: str) -> None:
        if not bank_name.strip():
            raise ValueError("bank_name is required for a vendor bank account")
        if not account_holder_name.strip():
            raise ValueError("account_holder_name is required for a vendor bank account")

    @staticmethod
    def _validate_bank_identifiers(
        account_number: Optional[str],
        iban: Optional[str],
        ifsc_code: Optional[str],
    ) -> tuple:
        if not account_number and not iban:
            raise ValueError(
                "At least one of account_number or iban is required for a vendor bank account"
            )

        validated_account_number = (
            validate_bank_account_number(account_number) if account_number else None
        )
        validated_ifsc_code = validate_ifsc(ifsc_code) if ifsc_code else None

        return validated_account_number, validated_ifsc_code

    def _bank_duplicate_across_vendors_enabled(self) -> bool:
        config_value = self.vendor_dao.get_config_value(
            BANK_DUPLICATE_ACROSS_VENDORS_CONFIG_KEY
        )
        return (config_value or "").strip().lower() == "true"

    def _check_bank_duplicates(
        self,
        vendor_id: int,
        account_number: Optional[str],
        iban: Optional[str],
    ) -> None:
        if self.vendor_dao.account_identifier_exists_for_vendor(vendor_id, account_number, iban):
            raise ValueError("This account_number/iban already exists for this vendor")

        if self._bank_duplicate_across_vendors_enabled() and self.vendor_dao.account_identifier_exists_across_vendors(
            account_number, iban, exclude_vendor_id=vendor_id
        ):
            raise ValueError("This account_number/iban already exists for another vendor")

    @staticmethod
    def _bank_snapshot(bank: VendorBank) -> dict:
        return {
            "bank_name": bank.bank_name,
            "account_holder_name": bank.account_holder_name,
            "account_number": bank.account_number,
            "iban": bank.iban,
            "swift_code": bank.swift_code,
            "routing_number": bank.routing_number,
            "ifsc_code": bank.ifsc_code,
            "is_primary": bank.is_primary,
        }

    # =========================================================
    # Vendor Tax (scoped to a single vendor address — e.g. a GST
    # registration tied to the address in that state)
    # =========================================================

    def create_tax(
        self,
        vendor_address_id: int,
        data: VendorTaxCreateRequest,
        user_id: str,
    ) -> VendorTax:

        self._require_address(vendor_address_id)

        registration_type, registration_number = self._validate_tax_fields(
            data.registration_type, data.registration_number
        )

        if self.vendor_dao.get_vendor_tax_by_registration_type(
            vendor_address_id, registration_type
        ) is not None:
            raise ValueError(
                "A tax registration of this type already exists for the address"
            )

        tax = VendorTax(
            vendor_address_id=vendor_address_id,
            registration_type=registration_type,
            registration_number=registration_number,
            is_verified=data.is_verified,
        )
        self.vendor_dao.create_vendor_tax(tax)

        self._write_audit(
            table_name="vendor_tax",
            record_id=tax.vendor_tax_id,
            action="CREATE",
            changed_by=user_id,
            new_values=self._tax_snapshot(tax),
        )

        self.db.commit()
        self.db.refresh(tax)

        return tax

    def list_taxes(self, vendor_address_id: int) -> List[VendorTax]:
        self._require_address(vendor_address_id)
        return self.vendor_dao.get_taxes_by_address(vendor_address_id)

    def get_tax(self, vendor_address_id: int, vendor_tax_id: int) -> VendorTax:
        self._require_address(vendor_address_id)
        tax = self.vendor_dao.get_vendor_tax_by_id(vendor_address_id, vendor_tax_id)
        if tax is None:
            raise ValueError("Tax not found")
        return tax

    def update_tax(
        self,
        vendor_address_id: int,
        vendor_tax_id: int,
        data: VendorTaxUpdateRequest,
        user_id: str,
    ) -> VendorTax:

        self._require_address(vendor_address_id)
        tax = self.vendor_dao.get_vendor_tax_by_id(vendor_address_id, vendor_tax_id)
        if tax is None:
            raise ValueError("Tax not found")

        before = self._tax_snapshot(tax)

        target_registration_type = (
            data.registration_type
            if data.registration_type is not None
            else tax.registration_type
        )
        target_registration_number = (
            data.registration_number
            if data.registration_number is not None
            else tax.registration_number
        )

        if data.registration_type is not None and data.registration_type != tax.registration_type:
            if self.vendor_dao.get_vendor_tax_by_registration_type(
                vendor_address_id, data.registration_type, exclude_vendor_tax_id=vendor_tax_id
            ) is not None:
                raise ValueError(
                    "A tax registration of this type already exists for the address"
                )

        registration_type, registration_number = self._validate_tax_fields(
            target_registration_type, target_registration_number
        )

        tax.registration_type = registration_type
        tax.registration_number = registration_number

        if data.registration_type is not None or data.registration_number is not None:
            tax.is_verified = False
            tax.verified_at = None

        after = self._tax_snapshot(tax)
        changed = {key: value for key, value in after.items() if before.get(key) != value}

        if changed:
            self._write_audit(
                table_name="vendor_tax",
                record_id=tax.vendor_tax_id,
                action="UPDATE",
                changed_by=user_id,
                old_values={key: before.get(key) for key in changed},
                new_values=changed,
            )

        self.db.commit()
        self.db.refresh(tax)

        return tax

    def delete_tax(self, vendor_address_id: int, vendor_tax_id: int, user_id: str) -> None:
        self._require_address(vendor_address_id)
        tax = self.vendor_dao.get_vendor_tax_by_id(vendor_address_id, vendor_tax_id)
        if tax is None:
            raise ValueError("Tax not found")

        self._write_audit(
            table_name="vendor_tax",
            record_id=tax.vendor_tax_id,
            action="DELETE",
            changed_by=user_id,
            old_values=self._tax_snapshot(tax),
        )

        self.vendor_dao.delete_vendor_tax(tax)
        self.db.commit()

    @staticmethod
    def _validate_tax_fields(registration_type: str, registration_number: str) -> tuple:
        if not registration_type.strip():
            raise ValueError("registration_type is required for a vendor tax entry")
        if not registration_number.strip():
            raise ValueError("registration_number is required for a vendor tax entry")

        return registration_type.strip().upper(), registration_number.strip().upper()

    @staticmethod
    def _tax_snapshot(tax: VendorTax) -> dict:
        return {
            "registration_type": tax.registration_type,
            "registration_number": tax.registration_number,
            "is_verified": tax.is_verified,
        }

    # =========================================================
    # Internal helpers — shared
    # =========================================================

    def _require_vendor(self, vendor_id: int) -> Vendor:
        vendor = self.vendor_dao.get_vendor_by_id(vendor_id)
        if vendor is None:
            raise ValueError("Vendor not found")
        return vendor

    def _require_address(self, vendor_address_id: int) -> None:
        if not self.vendor_dao.address_exists(vendor_address_id):
            raise ValueError("Address not found")

    def _resolve_status_id(self, status_id: Optional[int]) -> Optional[int]:
        if status_id is not None:
            status = self.vendor_dao.get_status_by_id(status_id)
            if status is None or status.module_name != VENDOR_STATUS_MODULE:
                raise ValueError(
                    f"status_id must reference a valid {VENDOR_STATUS_MODULE} status"
                )
            return status.status_id

        default_status = self.vendor_dao.get_status_by_module_code(
            VENDOR_STATUS_MODULE, DEFAULT_VENDOR_STATUS_CODE
        )
        return default_status.status_id if default_status else None

    # =========================================================
    # Internal helpers — audit trail
    # =========================================================

    @staticmethod
    def _snapshot(vendor: Vendor) -> dict:
        return {
            "vendor_name": vendor.vendor_name,
            "vendor_code": vendor.vendor_code,
            "country_id": vendor.country_id,
            "payment_term_id": vendor.payment_term_id,
            "currency_id": vendor.currency_id,
            "pan_number": vendor.pan_number,
            "phone_number": vendor.phone_number,
            "email": vendor.email,
            "status_id": vendor.status_id,
        }

    def _write_audit(
        self,
        table_name: str,
        record_id: int,
        action: str,
        changed_by: str,
        old_values: Optional[dict] = None,
        new_values: Optional[dict] = None,
    ) -> None:

        self.vendor_dao.create_audit_log(
            AuditLog(
                table_name=table_name,
                record_id=record_id,
                action=action,
                changed_by=changed_by,
                old_values=old_values,
                new_values=new_values,
            )
        )
