-- TDS Configuration backend (rules / payment natures / deductors / Excel import).
-- Same hand-applied convention as migration_tds_foundation.sql (this app has
-- no migration tool). Additive only - no existing table is dropped, no
-- invoice_tds snapshot row is touched. Safe to re-run: CREATE TABLE IF NOT
-- EXISTS, ADD COLUMN IF NOT EXISTS, guarded ADD CONSTRAINT, CREATE INDEX IF
-- NOT EXISTS, and data statements guarded by NOT EXISTS / IS NULL.
--
-- MUST be applied before deploying the matching code: models/master.py's
-- TaxRule now maps old_section/new_section/tds_deductor_id, so every
-- tax_rule query (including GST rate lookups) fails until these columns exist.
--
-- Rollback: see migration_tds_configuration_rollback.sql.

BEGIN;

-- ---------------------------------------------------------------
-- 1) Deductor master. TDS-only concept (the payer category a TDS section
--    applies to), so a TDS table rather than a generic-engine one - same
--    shape/conventions as ap.tds_payment_nature.
-- ---------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ap.tds_deductor (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY,
    code        VARCHAR(50)  NOT NULL,
    name        VARCHAR(150) NOT NULL,
    description TEXT,
    is_active   BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT tds_deductor_pkey PRIMARY KEY (id),
    CONSTRAINT tds_deductor_code_key UNIQUE (code)
);
CREATE INDEX IF NOT EXISTS idx_tds_deductor_active ON ap.tds_deductor (is_active);

-- ---------------------------------------------------------------
-- 2) TDS extension columns on the generic tax_rule (same precedent as
--    legal_reference/threshold_* in migration_tds_foundation.sql). All
--    nullable and meaningless for GST_RATE/TAX_COMPONENT rows.
--
--    old_section / new_section: the frontend's "Old Section" (Income-tax
--    Act 1961 numbering, e.g. 194C) and "New Section" (numbering under the
--    replacement Act). Kept apart from rule_code, which is now a per-VARIANT
--    business key (several rule_codes can share one section).
--    tds_deductor_id: FK to the deductor master instead of repeated text.
-- ---------------------------------------------------------------
ALTER TABLE ap.tax_rule ADD COLUMN IF NOT EXISTS old_section VARCHAR(20);
ALTER TABLE ap.tax_rule ADD COLUMN IF NOT EXISTS new_section VARCHAR(20);
ALTER TABLE ap.tax_rule ADD COLUMN IF NOT EXISTS tds_deductor_id INTEGER;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'tax_rule_tds_deductor_fk') THEN
        ALTER TABLE ap.tax_rule ADD CONSTRAINT tax_rule_tds_deductor_fk
            FOREIGN KEY (tds_deductor_id) REFERENCES ap.tds_deductor (id) ON DELETE RESTRICT;
    END IF;
END $$;

-- ---------------------------------------------------------------
-- 2b) invoice_tds snapshot completeness. Rules are now editable from the
--     UI, so the snapshot must describe itself without relying on the live
--     tax_rule row: threshold_type (threshold_amount was already stored),
--     residency_type (a rate-condition input alongside entity_type), and
--     rule_snapshot - the rule variant exactly as applied (rule_code,
--     sections, deductor, rate condition, rate row). Nullable/additive;
--     existing rows keep NULL (they were determined before rules were
--     editable, so their FK'd rows are still what was applied).
-- ---------------------------------------------------------------
ALTER TABLE ap.invoice_tds ADD COLUMN IF NOT EXISTS threshold_type VARCHAR(20);
ALTER TABLE ap.invoice_tds ADD COLUMN IF NOT EXISTS residency_type VARCHAR(30);
ALTER TABLE ap.invoice_tds ADD COLUMN IF NOT EXISTS rule_snapshot JSONB;

-- ---------------------------------------------------------------
-- 3) Lookup indexes for the rule engine / config list screens. The generic
--    tables had no index beyond their PKs.
-- ---------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_tax_rule_category_active ON ap.tax_rule (rule_category, is_active);
CREATE INDEX IF NOT EXISTS idx_tax_rule_tds_deductor ON ap.tax_rule (tds_deductor_id);
CREATE INDEX IF NOT EXISTS idx_tax_rule_old_section ON ap.tax_rule (old_section);
CREATE INDEX IF NOT EXISTS idx_tax_rule_condition_rule ON ap.tax_rule_condition (tax_rule_id);
CREATE INDEX IF NOT EXISTS idx_tax_rule_condition_type_value ON ap.tax_rule_condition (condition_type, condition_value);
CREATE INDEX IF NOT EXISTS idx_tax_rate_rule_rule ON ap.tax_rate_rule (tax_rule_id);
CREATE INDEX IF NOT EXISTS idx_invoice_tds_rate_rule ON ap.invoice_tds (tds_rate_rule_id);
CREATE INDEX IF NOT EXISTS idx_invoice_tds_payment_nature ON ap.invoice_tds (payment_nature_id);

-- ---------------------------------------------------------------
-- 4) Data: backfill old_section for the seeded TDS rules from their
--    rule_code (TDS_194C -> 194C). Only fills NULLs, never overwrites.
--    new_section is deliberately NOT guessed - Finance sets it via the UI.
-- ---------------------------------------------------------------
UPDATE ap.tax_rule
SET old_section = substring(rule_code FROM '^TDS_([0-9]+[A-Z]*)$'),
    updated_at = CURRENT_TIMESTAMP
WHERE rule_category = 'TDS_RATE'
  AND old_section IS NULL
  AND rule_code ~ '^TDS_[0-9]+[A-Z]*$';

-- ---------------------------------------------------------------
-- 5) Data: one payment nature per rule variant. The TDS Configuration UI
--    models a rule as ONE "Nature of Payment"; live TDS_194J carried two
--    PAYMENT_NATURE conditions (PROFESSIONAL_SERVICE and TECHNICAL_SERVICE).
--    Split TECHNICAL_SERVICE into its own variant TDS_194J_TECH with the
--    SAME rate, threshold and dates, so determination results do not change.
--    (Finance can later set the technical-service rate via the UI.)
--    The existing condition row is MOVED, not deleted-and-recreated.
--    Historical invoice_tds rows keep pointing at TDS_194J / its rate row.
-- ---------------------------------------------------------------
INSERT INTO ap.tax_rule (
    rule_code, rule_name, tax_type_id, rule_category, description, priority,
    effective_from, effective_to, is_active, created_by, legal_reference,
    threshold_amount, threshold_type, old_section, new_section, tds_deductor_id
)
SELECT
    'TDS_194J_TECH', 'TDS - Technical Services', r.tax_type_id, r.rule_category,
    'TDS applicable on technical service payments under Section 194J (split from TDS_194J)',
    r.priority, r.effective_from, r.effective_to, r.is_active, 'migration_tds_configuration',
    r.legal_reference, r.threshold_amount, r.threshold_type, r.old_section, r.new_section, r.tds_deductor_id
FROM ap.tax_rule r
WHERE r.rule_code = 'TDS_194J'
  AND EXISTS (
      SELECT 1 FROM ap.tax_rule_condition c
      WHERE c.tax_rule_id = r.tax_rule_id
        AND c.condition_type = 'PAYMENT_NATURE'
        AND c.condition_value = 'TECHNICAL_SERVICE'
  )
  AND NOT EXISTS (SELECT 1 FROM ap.tax_rule WHERE rule_code = 'TDS_194J_TECH');

INSERT INTO ap.tax_rate_rule (tax_rule_id, rate_percent, calculation_type, fixed_amount, effective_from, effective_to, is_active, created_by)
SELECT tech.tax_rule_id, rr.rate_percent, rr.calculation_type, rr.fixed_amount, rr.effective_from, rr.effective_to, rr.is_active, 'migration_tds_configuration'
FROM ap.tax_rule tech
JOIN ap.tax_rule src ON src.rule_code = 'TDS_194J'
JOIN ap.tax_rate_rule rr ON rr.tax_rule_id = src.tax_rule_id AND rr.is_active = TRUE
WHERE tech.rule_code = 'TDS_194J_TECH'
  AND NOT EXISTS (SELECT 1 FROM ap.tax_rate_rule x WHERE x.tax_rule_id = tech.tax_rule_id);

UPDATE ap.tax_rule_condition c
SET tax_rule_id = tech.tax_rule_id, updated_at = CURRENT_TIMESTAMP
FROM ap.tax_rule src, ap.tax_rule tech
WHERE src.rule_code = 'TDS_194J'
  AND tech.rule_code = 'TDS_194J_TECH'
  AND c.tax_rule_id = src.tax_rule_id
  AND c.condition_type = 'PAYMENT_NATURE'
  AND c.condition_value = 'TECHNICAL_SERVICE';

-- TDS_194J's rule_name is intentionally left as-is: verified invoice
-- snapshots display it, and renaming is a Finance decision (editable in the UI).

COMMIT;

-- Verification:
--   SELECT tax_rule_id, rule_code, old_section, new_section, tds_deductor_id
--   FROM ap.tax_rule WHERE rule_category = 'TDS_RATE' ORDER BY rule_code;       -- 6 rows, old_section populated
--
--   SELECT r.rule_code, c.condition_value FROM ap.tax_rule_condition c
--   JOIN ap.tax_rule r USING (tax_rule_id)
--   WHERE c.condition_type = 'PAYMENT_NATURE' ORDER BY 1;                         -- exactly one nature per rule
--
--   SELECT r.rule_code, rr.rate_percent FROM ap.tax_rate_rule rr
--   JOIN ap.tax_rule r USING (tax_rule_id) WHERE r.rule_code LIKE 'TDS_194J%';   -- both 10.0000
