-- Payment-term compliance (APM_AUTOMATION_PLAN.md 3.1 / 3.1a / 3.2):
--   * vendor MSME classification (statutory MSMED Act payment limit)
--   * structured payment term on purchase orders (free-text column kept)
--   * vendor agreements / contracts + their documents
--   * per-invoice payment-term compliance record
--   * statutory-limit configuration rows
--
-- Same hand-applied convention as the other migration_*.sql files. Additive
-- only - no existing row is updated or deleted; safe to re-run.
-- Rollback: migration_payment_term_compliance_rollback.sql.
--
-- MUST be applied before deploying the matching code: models/vendor.py and
-- models/purchase_order.py map the new columns, so every vendor / PO query
-- fails until they exist. (create_all at startup only creates missing
-- TABLES, never missing columns.)

BEGIN;

-- ---------------------------------------------------------------
-- 1) Vendor MSME classification. Only MICRO / SMALL enterprises get the
--    MSMED Act s.15 payment limit (and Income-tax s.43B(h)); MEDIUM is
--    recorded for completeness.
-- ---------------------------------------------------------------
ALTER TABLE ap.vendor ADD COLUMN IF NOT EXISTS msme_registered BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE ap.vendor ADD COLUMN IF NOT EXISTS udyam_number VARCHAR(19);
ALTER TABLE ap.vendor ADD COLUMN IF NOT EXISTS msme_category VARCHAR(10);
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'vendor_msme_category_chk') THEN
        ALTER TABLE ap.vendor ADD CONSTRAINT vendor_msme_category_chk
            CHECK (msme_category IS NULL OR msme_category IN ('MICRO', 'SMALL', 'MEDIUM'));
    END IF;
END $$;

-- ---------------------------------------------------------------
-- 2) Purchase order: structured payment term. The free-text
--    payment_terms column stays (existing POs are parsed from it).
-- ---------------------------------------------------------------
ALTER TABLE ap.purchase_order ADD COLUMN IF NOT EXISTS payment_term_id INTEGER;
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_po_payment_term') THEN
        ALTER TABLE ap.purchase_order ADD CONSTRAINT fk_po_payment_term
            FOREIGN KEY (payment_term_id) REFERENCES ap.payment_term (payment_term_id);
    END IF;
END $$;

-- ---------------------------------------------------------------
-- 3) Vendor agreements / contracts. Only an ACTIVE (verified) agreement
--    valid on the invoice date is an authoritative payment-term source.
--    "Expired" is computed from valid_to, never stored.
-- ---------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ap.vendor_agreement (
    agreement_id          INTEGER GENERATED BY DEFAULT AS IDENTITY,
    vendor_id             INTEGER      NOT NULL,
    agreement_type        VARCHAR(20)  NOT NULL DEFAULT 'OTHER',
    reference_no          VARCHAR(100),
    title                 VARCHAR(200) NOT NULL,
    valid_from            DATE         NOT NULL,
    valid_to              DATE,
    auto_renew            BOOLEAN      NOT NULL DEFAULT FALSE,
    payment_term_id       INTEGER,
    payment_terms_text    VARCHAR(500),
    term_days             SMALLINT,
    due_basis             VARCHAR(20)  NOT NULL DEFAULT 'INVOICE_DATE',
    status                VARCHAR(25)  NOT NULL DEFAULT 'PENDING_VERIFICATION',
    extracted_payload     JSONB,
    extraction_confidence NUMERIC(5, 2),
    remarks               TEXT,
    uploaded_by           VARCHAR(100),
    uploaded_at           TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    verified_by           VARCHAR(100),
    verified_at           TIMESTAMP,
    verification_remarks  TEXT,
    updated_by            VARCHAR(100),
    updated_at            TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT vendor_agreement_pkey PRIMARY KEY (agreement_id),
    CONSTRAINT vendor_agreement_vendor_fk FOREIGN KEY (vendor_id)
        REFERENCES ap.vendor (vendor_id),
    CONSTRAINT vendor_agreement_payment_term_fk FOREIGN KEY (payment_term_id)
        REFERENCES ap.payment_term (payment_term_id),
    CONSTRAINT vendor_agreement_type_chk CHECK (
        agreement_type IN ('LEASE', 'MSA', 'SOW', 'SUBSCRIPTION', 'RATE_CONTRACT', 'OTHER')),
    CONSTRAINT vendor_agreement_status_chk CHECK (
        status IN ('DRAFT', 'PENDING_VERIFICATION', 'ACTIVE', 'REJECTED', 'SUPERSEDED')),
    CONSTRAINT vendor_agreement_due_basis_chk CHECK (due_basis IN ('INVOICE_DATE', 'GRN_DATE')),
    CONSTRAINT vendor_agreement_term_days_chk CHECK (term_days IS NULL OR term_days BETWEEN 0 AND 365),
    CONSTRAINT vendor_agreement_validity_chk CHECK (valid_to IS NULL OR valid_to >= valid_from)
);
CREATE INDEX IF NOT EXISTS idx_vendor_agreement_vendor_status ON ap.vendor_agreement (vendor_id, status);

CREATE TABLE IF NOT EXISTS ap.vendor_agreement_document (
    document_id   INTEGER GENERATED BY DEFAULT AS IDENTITY,
    agreement_id  INTEGER      NOT NULL,
    file_name     VARCHAR(255) NOT NULL,
    file_path     VARCHAR(500) NOT NULL,
    content_type  VARCHAR(100),
    file_size     INTEGER,
    uploaded_by   VARCHAR(100),
    uploaded_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT vendor_agreement_document_pkey PRIMARY KEY (document_id),
    CONSTRAINT vendor_agreement_document_agreement_fk FOREIGN KEY (agreement_id)
        REFERENCES ap.vendor_agreement (agreement_id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_vendor_agreement_document_agreement ON ap.vendor_agreement_document (agreement_id);

-- ---------------------------------------------------------------
-- 4) Per-invoice payment-term compliance (1:1 with invoice). Keeps the
--    invoice-stated, PO, agreement and vendor-master terms side by side,
--    and the contractual / statutory / effective due dates apart.
--    invoice.due_date mirrors effective_due_date so existing queries keep
--    working. OVERDUE is computed at query time, never stored.
-- ---------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ap.invoice_payment_term (
    invoice_id                 INTEGER      NOT NULL,
    invoice_terms_text         VARCHAR(500),
    invoice_term_days          SMALLINT,
    invoice_due_date_printed   DATE,
    po_terms_text              VARCHAR(500),
    po_term_days               SMALLINT,
    vendor_master_term_id      INTEGER,
    vendor_master_term_days    SMALLINT,
    agreement_id               INTEGER,
    agreement_term_days        SMALLINT,
    reference_source           VARCHAR(20)  NOT NULL DEFAULT 'NONE',
    applied_term_days          SMALLINT,
    suggested_term_days        SMALLINT,
    due_basis                  VARCHAR(20)  NOT NULL DEFAULT 'INVOICE_DATE',
    basis_date                 DATE,
    contractual_due_date       DATE,
    statutory_due_date         DATE,
    statutory_rule             VARCHAR(50),
    effective_due_date         DATE,
    due_date_verified          BOOLEAN      NOT NULL DEFAULT FALSE,
    validation_status          VARCHAR(20)  NOT NULL DEFAULT 'REVIEW_REQUIRED',
    reason_code                VARCHAR(50),
    reason_detail              VARCHAR(500),
    checked_at                 TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    verified_by                VARCHAR(100),
    verified_at                TIMESTAMP,
    verification_remarks       TEXT,
    created_at                 TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                 TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT invoice_payment_term_pkey PRIMARY KEY (invoice_id),
    CONSTRAINT invoice_payment_term_invoice_fk FOREIGN KEY (invoice_id)
        REFERENCES ap.invoice (invoice_id) ON DELETE CASCADE,
    CONSTRAINT invoice_payment_term_agreement_fk FOREIGN KEY (agreement_id)
        REFERENCES ap.vendor_agreement (agreement_id),
    CONSTRAINT invoice_payment_term_vendor_term_fk FOREIGN KEY (vendor_master_term_id)
        REFERENCES ap.payment_term (payment_term_id),
    CONSTRAINT invoice_payment_term_source_chk CHECK (
        reference_source IN ('PO', 'AGREEMENT', 'VENDOR_MASTER', 'MANUAL', 'NONE')),
    CONSTRAINT invoice_payment_term_basis_chk CHECK (due_basis IN ('INVOICE_DATE', 'GRN_DATE')),
    CONSTRAINT invoice_payment_term_status_chk CHECK (
        validation_status IN ('COMPLIANT', 'MISMATCH', 'REVIEW_REQUIRED', 'VERIFIED_OVERRIDE'))
);
CREATE INDEX IF NOT EXISTS idx_invoice_payment_term_status ON ap.invoice_payment_term (validation_status);
CREATE INDEX IF NOT EXISTS idx_invoice_payment_term_effective_due ON ap.invoice_payment_term (effective_due_date);

-- ---------------------------------------------------------------
-- 5) Statutory payment limits as configuration, not code (MSMED Act s.15:
--    agreed period may not exceed 45 days; 15 days when nothing is agreed).
-- ---------------------------------------------------------------
INSERT INTO ap.system_configuration (config_key, config_value, data_type, description)
VALUES
    ('MSME_MAX_PAYMENT_DAYS', '45', 'NUMBER',
     'MSMED Act s.15: maximum agreed payment period (days) for MICRO/SMALL suppliers'),
    ('MSME_DEFAULT_PAYMENT_DAYS', '15', 'NUMBER',
     'MSMED Act s.15: payment period (days) for MICRO/SMALL suppliers when no period is agreed')
ON CONFLICT (config_key) DO NOTHING;

COMMIT;
