-- Payment Management (record externally completed payments + receipts) and
-- TDS Tracking (deduction / deposit / filing recorded from outside systems).
-- Same hand-applied convention as the other migration_*.sql files. Additive
-- only; safe to re-run. Rollback: migration_payment_tds_tracking_rollback.sql.
--
-- MUST be applied before deploying the matching code (models/payment.py maps
-- payment.remarks, so every payment query fails until the column exists).

BEGIN;

-- ---------------------------------------------------------------
-- 1) ap.payment: free-text remarks entered when recording a payment.
--    The existing columns already cover the rest of the Record Payment
--    form: payment_date, total_amount, payment_method (mode),
--    reference_number (UTR / cheque no.), created_by (recorded by).
-- ---------------------------------------------------------------
ALTER TABLE ap.payment ADD COLUMN IF NOT EXISTS remarks TEXT;

-- ---------------------------------------------------------------
-- 2) Payment receipts / proof. One payment can carry several files.
--    Stored in S3 via the same upload_to_s3 helper every other AP upload
--    uses; file_path is the S3 object key.
-- ---------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ap.payment_document (
    payment_document_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    payment_id          INTEGER      NOT NULL,
    document_type       VARCHAR(30)  NOT NULL DEFAULT 'RECEIPT',
    file_name           VARCHAR(255) NOT NULL,
    file_path           VARCHAR(500) NOT NULL,
    content_type        VARCHAR(100),
    file_size           INTEGER,
    uploaded_by         VARCHAR(100),
    uploaded_at         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT payment_document_pkey PRIMARY KEY (payment_document_id),
    CONSTRAINT payment_document_payment_fk FOREIGN KEY (payment_id)
        REFERENCES ap.payment (payment_id) ON DELETE CASCADE,
    CONSTRAINT payment_document_type_chk CHECK (document_type IN ('RECEIPT', 'OTHER'))
);
CREATE INDEX IF NOT EXISTS idx_payment_document_payment ON ap.payment_document (payment_id);
CREATE INDEX IF NOT EXISTS idx_payment_invoice_invoice_payment ON ap.payment_invoice (invoice_id, payment_id);

-- ---------------------------------------------------------------
-- 3) TDS tracking: the post-verification lifecycle of the TDS withheld on
--    an invoice. Kept OUT of ap.invoice_tds on purpose - that row is the
--    determination snapshot (immutable once VERIFIED); this one records
--    what Finance did about it afterwards, outside this system.
--    One row per invoice, created on the first recorded activity; an
--    invoice with tds_applicable=true and no row is TDS_PENDING.
--    TDS_PENDING -> TDS_DEDUCTED -> TDS_DEPOSITED -> TDS_FILED
-- ---------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ap.invoice_tds_tracking (
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY,
    invoice_id         INTEGER      NOT NULL,
    tracking_status    VARCHAR(30)  NOT NULL DEFAULT 'TDS_PENDING',
    deduction_date     DATE,
    challan_number     VARCHAR(50),
    bsr_code           VARCHAR(20),
    deposit_date       DATE,
    filing_date        DATE,
    filing_reference   VARCHAR(100),
    remarks            TEXT,
    created_by         VARCHAR(100),
    created_at         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by         VARCHAR(100),
    updated_at         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT invoice_tds_tracking_pkey PRIMARY KEY (id),
    CONSTRAINT invoice_tds_tracking_invoice_unique UNIQUE (invoice_id),
    CONSTRAINT invoice_tds_tracking_invoice_fk FOREIGN KEY (invoice_id)
        REFERENCES ap.invoice (invoice_id) ON DELETE CASCADE,
    CONSTRAINT invoice_tds_tracking_status_chk
        CHECK (tracking_status IN ('TDS_PENDING', 'TDS_DEDUCTED', 'TDS_DEPOSITED', 'TDS_FILED')),
    CONSTRAINT invoice_tds_tracking_dates_chk CHECK (
        (deposit_date IS NULL OR deduction_date IS NULL OR deposit_date >= deduction_date)
        AND (filing_date IS NULL OR deposit_date IS NULL OR filing_date >= deposit_date)
    )
);
CREATE INDEX IF NOT EXISTS idx_invoice_tds_tracking_status ON ap.invoice_tds_tracking (tracking_status);

CREATE TABLE IF NOT EXISTS ap.invoice_tds_document (
    id                       INTEGER GENERATED BY DEFAULT AS IDENTITY,
    invoice_tds_tracking_id  INTEGER      NOT NULL,
    document_type            VARCHAR(30)  NOT NULL DEFAULT 'OTHER',
    file_name                VARCHAR(255) NOT NULL,
    file_path                VARCHAR(500) NOT NULL,
    content_type             VARCHAR(100),
    file_size                INTEGER,
    uploaded_by              VARCHAR(100),
    uploaded_at              TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT invoice_tds_document_pkey PRIMARY KEY (id),
    CONSTRAINT invoice_tds_document_tracking_fk FOREIGN KEY (invoice_tds_tracking_id)
        REFERENCES ap.invoice_tds_tracking (id) ON DELETE CASCADE,
    CONSTRAINT invoice_tds_document_type_chk
        CHECK (document_type IN ('CHALLAN', 'CERTIFICATE', 'FILING_ACKNOWLEDGEMENT', 'OTHER'))
);
CREATE INDEX IF NOT EXISTS idx_invoice_tds_document_tracking ON ap.invoice_tds_document (invoice_tds_tracking_id);

CREATE INDEX IF NOT EXISTS idx_invoice_tds_applicable ON ap.invoice_tds (tds_applicable);

COMMIT;
